[package]
name = "MyPlayer"
version = "0.1.0"
edition = "2021"
author = "Thomas Lee <thomasyanli007@gmail.com>"
description = "A simple audio player written in Rust"
license = "MIT"


[dependencies]
rodio="0.19.0"
glob = "0.3.0" 
rand = "0.8.4"
